apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffhs-devops
  labels:
    app: personalstock
  namespace: ffhs-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffhs-devops
  template:
    metadata:
      labels:
        app: ffhs-devops
    spec:
      containers:
      - name: personalstock
        image: eu.gcr.io/ffhsdevopsalejandro/personal-stock:1.0
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: svc-personalstock
  namespace: ffhs-devops
spec:
  type: NodePort
  selector:
    ffhs-devops: web
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001